name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Configure Git identity
      run: |
        git config user.name 'Jordi Izquierdo'
        git config user.email 'jordi.izquierdo.casares@gmail.com'

    - name: Move dist files to another branch
      run: |
        git checkout -b dist-branch
        git add dist --force
        git commit -m "Add distribution files"
        git push origin dist-branch

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2

    - name: Push dist files to GitHub Pages branch
      run: |
        git checkout dist-branch
        git push origin dist-branch --force
