on:
  pull_request:
    branches:
      - development

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2

    - name: Install dependencies
      run: yarn

    - name: Run Tests
      run: yarn test
