name: Test

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run test
